Description: CloudFormation template for creating Standard AD
Outputs:
  ADDomainID:
    Description: ID of the newly Created AD
    Value: !Ref 'InsLakeAD'
  ADIPAddress:
    Description: IP addresses of newly Created AD
    Value: !Select
      - '1'
      - !GetAtt 'InsLakeAD.DnsIpAddresses'
Parameters:
  DomainName:
    Default: ins.data.lake
    Description: DomainName
    AllowedValues:
      - ins.data.lake
    Type: String
  DomainPassword:
    Description: DomainPassword
    Type: String
  DomainShortName:
    Default: InsLakeAD
    Description: DomainShortName
    Type: String
  Subnet1AD:
    Description: Subnet ID1 for creating the Microsoft Standard AD
    Type: AWS::EC2::Subnet::Id
  Subnet2AD:
    Description: Subnet ID2 for creating the Microsoft Standard AD
    Type: AWS::EC2::Subnet::Id
  VPC:
    Description: VPC ID for Microsoft Standard AD and EMR Cluster
    Type: AWS::EC2::VPC::Id
Resources:
  InsLakeAD:
    Properties:
      CreateAlias: 'false'
      Edition: 'Standard'
      Name: !Ref 'DomainName'
      Password: !Ref 'DomainPassword'
      ShortName: !Ref 'DomainShortName'
      VpcSettings:
        SubnetIds:
          - !Ref 'Subnet1AD'
          - !Ref 'Subnet2AD'
        VpcId: !Ref 'VPC'
    Type: AWS::DirectoryService::MicrosoftAD
